from __future__ import annotations

import copy
from typing import Any

from api.config_api import _PAGE_PERSISTED_FIELDS
from core.exceptions import ConfigNotFoundError, ConfigValidationError
from core.ids import slug_id
from core.page_index import contains_page, remove_page
from core.storage import (
    WIDGET_BUILD_DIR,
    active_config_dir,
    active_pages_dir,
    read_json,
    write_json,
)
from core.validation import build_context, validate_page
from core.validation.ids import is_valid_page_id
from core.validation.structure import load_widget_manifest
from services.websocket_manager import invalidate_runtime_pages_config_cache

from .. import idempotency, locks
from ..confirm import applied_response, dry_run_response
from ..pagination import paginated_payload
from ..server import expose_read_tool, get_agent_label, register_tool
from ..write_helpers import emit_change
from ._common import (
    apply_json_pointer,
    find_widget,
    insert_at_position,
    merge_patch,
    parent_children_list,
    raise_if_findings,
)

# Container-host widget types — mirrors frontend's CONTAINER_HOST_TYPES.
# Widgets of these types render as flex/grid containers and need a
# ``children`` array even when empty so the UI tree drop-targets work.
#
# Only the types compiled into the bundle are listed. Everything registered
# from a manifest — the stdlib's Container, and any project widget — declares
# it with ``export const hostsChildren = true`` instead, which is what
# ``_hosts_children`` below reads.
_CONTAINER_HOST_TYPES = frozenset({"ImageContainer"})


def _hosts_children(widget_type: str) -> bool:
    """Whether nodes of this type carry a ``children`` array.

    A project widget wins over a same-named stdlib one, mirroring the frontend
    registry's shadowing order. ``load_widget_manifest`` overlays the shipped
    stdlib onto ``builtin``, so hosting still resolves in a runtime home that
    has never compiled.
    """
    if widget_type in _CONTAINER_HOST_TYPES:
        return True
    manifest = load_widget_manifest()
    custom = manifest.get("custom")
    if isinstance(custom, dict):
        for key, entry in custom.items():
            # custom keys are "<Group>/<Name>"; widget types in pages are "<Name>".
            if key.split("/")[-1] == widget_type and isinstance(entry, dict):
                return entry.get("hostsChildren") is True
    builtin = manifest.get("builtin")
    entry = builtin.get(widget_type) if isinstance(builtin, dict) else None
    return isinstance(entry, dict) and entry.get("hostsChildren") is True

# Top-level page fields that pages_set_metadata may patch. ``id`` and
# ``sections`` are excluded — renames and structural rewrites must go through
# dedicated tools (pages_create / pages_add_widget / pages_delete_widget).
# Mirrors ``_PAGE_PERSISTED_FIELDS`` from the REST PUT handler so MCP- and
# REST-written pages round-trip through the same allowlist.
_PAGE_METADATA_FIELDS = _PAGE_PERSISTED_FIELDS - {"sections"}


def _collect_widget_ids(node: Any, acc: set[str]) -> None:
    """Gather every string ``id`` found anywhere in a page structure."""
    if isinstance(node, dict):
        wid = node.get("id")
        if isinstance(wid, str) and wid:
            acc.add(wid)
        for value in node.values():
            _collect_widget_ids(value, acc)
    elif isinstance(node, list):
        for item in node:
            _collect_widget_ids(item, acc)


def _assign_fresh_widget_ids(node: Any, taken: set[str]) -> None:
    """Recursively assign unique slug IDs to every widget dict in *node*.

    Agent-supplied subtrees may already contain ``id`` keys — copy-pasted from
    another page, generated by an earlier prompt, etc. Rewriting them here
    keeps page-wide widget IDs unique, which the frontend tree relies on.
    Slugs are derived from the widget's instance/catalog name and disambiguated against
    *taken* (which the caller seeds with IDs already on the page).
    """
    if isinstance(node, dict):
        if "type" in node:
            base = node.get("name") or _widget_name_for(str(node.get("type", ""))) or "widget"
            node["id"] = slug_id(str(base), taken)
            taken.add(node["id"])
        children = node.get("children")
        if isinstance(children, list):
            for child in children:
                _assign_fresh_widget_ids(child, taken)


_name_lookup_cache: tuple[int, int, dict[str, str]] | None = None


def _widget_name_for(widget_type: str) -> str:
    """Return the catalog name for ``widget_type``, falling back to the type itself.

    Keys the flat ``widget_type → name`` map on ``(mtime_ns, id(manifest))``:
    object identity alone can be misleading because ``load_widget_manifest``
    may return the same dict from different mtime paths during testing or
    hot-reload.
    """
    global _name_lookup_cache
    manifest = load_widget_manifest()
    try:
        mtime = (WIDGET_BUILD_DIR / "widget-schemas.json").stat().st_mtime_ns
    except FileNotFoundError:
        mtime = 0
    if (
        _name_lookup_cache is None
        or _name_lookup_cache[0] != mtime
        or _name_lookup_cache[1] != id(manifest)
    ):
        lookup: dict[str, str] = {}
        for type_name, entry in manifest.get("builtin", {}).items():
            name = entry.get("name") if isinstance(entry, dict) else None
            if isinstance(name, str) and name:
                lookup[type_name] = name
        for key, entry in manifest.get("custom", {}).items():
            name = entry.get("name") if isinstance(entry, dict) else None
            if isinstance(name, str) and name:
                lookup[key.split("/")[-1]] = name
        _name_lookup_cache = (mtime, id(manifest), lookup)
    return _name_lookup_cache[2].get(widget_type, widget_type)


def _read_page(page_id: str) -> dict[str, Any]:
    """Read an existing, indexed page for mutation. Never creates one.

    Every mutation tool but ``pages_create`` reads through here, so missing or
    unindexed pages fail closed with a stable not-found error instead of the
    old default-empty-page fallback (which let e.g. ``pages_add_widget`` on a
    typo'd ``page_id`` silently create an orphan file outside the page index).
    Both a missing file and an on-disk file absent from the ``config.json``
    index count as not-found — only ``pages_create`` may create *and* index a
    page in the same operation.
    """
    path = active_pages_dir() / f"{page_id}.json"
    if not path.exists():
        raise ConfigNotFoundError(f"Page '{page_id}' not found")
    config = _read_config_index()
    pages_index = config.get("pages")
    if not isinstance(pages_index, list) or not contains_page(pages_index, page_id):
        raise ConfigNotFoundError(f"Page '{page_id}' not found")
    return read_json(path)


def _write_page(page_id: str, payload: dict[str, Any]) -> None:
    write_json(active_pages_dir() / f"{page_id}.json", payload)
    invalidate_runtime_pages_config_cache()


def _write_config_index(config: dict[str, Any]) -> None:
    write_json(_config_path(), config)
    invalidate_runtime_pages_config_cache()


def _validate_page_or_raise(page: dict[str, Any]) -> list[dict[str, Any]]:
    """Validate, raise on findings, return advisory warnings (if any).

    Warnings ride along on every applied-response so MCP clients see typos
    in $var bindings etc. without losing the write.
    """
    report = validate_page(page, build_context())
    raise_if_findings(report)
    return report.to_dict()["warnings"]


def _config_path():
    return active_config_dir() / "config.json"


def _read_config_index() -> dict[str, Any]:
    path = _config_path()
    if not path.exists():
        return {"version": 2, "pages": []}
    raw = read_json(path)
    if not isinstance(raw, dict):
        return {"version": 2, "pages": []}
    return raw


def _pages_list_items() -> list[tuple[str, str, dict]]:
    config_path = active_config_dir() / "config.json"
    items: list[tuple[str, str, dict]] = []
    if not config_path.exists():
        return items
    try:
        config = read_json(config_path)
    except Exception:
        return items
    pages = config.get("pages", []) if isinstance(config, dict) else []

    def walk(nodes: list, prefix: str = "") -> None:
        for node in nodes:
            if not isinstance(node, dict):
                continue
            nid = node.get("id")
            if not isinstance(nid, str):
                continue
            if node.get("type") == "page-group":
                items.append(
                    (f"{prefix}{nid}", nid, {"id": nid, "type": "page-group", "label": node.get("label", nid)})
                )
                walk(node.get("children", []), f"{prefix}{nid}/")
            else:
                items.append((f"{prefix}{nid}", nid, {"id": nid, "type": "page"}))

    walk(pages)
    return items


def _get_page_payload(page_id: str) -> dict[str, Any]:
    if not is_valid_page_id(page_id):
        raise ConfigValidationError(f"Invalid page id: {page_id!r}")
    path = active_pages_dir() / f"{page_id}.json"
    if not path.exists():
        raise ConfigNotFoundError(f"Page '{page_id}' not found")
    return read_json(path)


def _pages_list_payload(cursor: str | None = None, limit: int | None = None) -> dict[str, Any]:
    return paginated_payload(_pages_list_items(), cursor=cursor, limit=limit)


pages_list = expose_read_tool(
    _pages_list_payload,
    name="pages_list",
    description=(
        "List page-index summaries. Returns ``{ items, next_cursor? }``. "
        "Pass ``next_cursor`` back as ``cursor`` to fetch the following page. "
        "Default page size 100, max 500. Each item has ``id`` and ``type`` "
        "(``page`` or ``page-group``); use ``pages_get`` for full page JSON."
    ),
)
pages_get = expose_read_tool(
    _get_page_payload,
    name="pages_get",
    description="Full page JSON. Widget IDs in the tree are stable mutation targets.",
)


@register_tool()
async def pages_create(
    title: str | None = None,
    route: str | None = None,
    layout: str | None = None,
    idempotency_key: str | None = None,
) -> dict[str, Any]:
    """Create a new page record. The server derives a slug page_id from the title.

    The new page is appended to the top-level page index in ``config.json``.
    """
    label = get_agent_label()
    if idempotency_key:
        cached = idempotency.get(label, idempotency_key)
        if cached is not None:
            return cached
    page_title = title if title is not None else "New Page"
    existing_page_ids = {f.stem for f in active_pages_dir().glob("*.json")}
    page_id = slug_id(page_title, existing_page_ids)
    payload: dict[str, Any] = {
        "id": page_id,
        "title": page_title,
        "sections": {"content": []},
    }
    if route is not None:
        payload["route"] = route
    if layout is not None:
        payload["layout"] = layout
    async with locks.acquire(("page", page_id), ("config", "config")):
        _write_page(page_id, payload)
        try:
            config = _read_config_index()
            pages_index = config.setdefault("pages", [])
            if isinstance(pages_index, list) and not contains_page(pages_index, page_id):
                pages_index.append({"id": page_id, "type": "page"})
                _write_config_index(config)
        except Exception:
            (active_pages_dir() / f"{page_id}.json").unlink(missing_ok=True)
            invalidate_runtime_pages_config_cache()
            raise
        response = applied_response(f"Created page '{page_id}'", None, payload)
        response["page_id"] = page_id
    await emit_change(
        artifact_type="page",
        artifact_ids=[page_id],
        summary=response["summary"],
        diff=response["diff"]
    )
    if idempotency_key:
        idempotency.put(label, idempotency_key, response)
    return response


@register_tool()
async def pages_delete(
    page_id: str,
    confirm: bool = False,
    idempotency_key: str | None = None,
) -> dict[str, Any]:
    """Delete a page. Two-step: dry-run unless ``confirm=true``.

    Also removes the page entry from the ``config.json`` index if present.
    """
    label = get_agent_label()
    if idempotency_key:
        cached = idempotency.get(label, idempotency_key)
        if cached is not None:
            return cached
    if not is_valid_page_id(page_id):
        raise ConfigValidationError("Invalid page_id")
    path = active_pages_dir() / f"{page_id}.json"
    if not confirm:
        try:
            preview_before = read_json(path)
        except FileNotFoundError:
            raise ConfigNotFoundError(f"Page '{page_id}' not found") from None
        return dry_run_response(f"Would delete page '{page_id}'", preview_before, None)
    async with locks.acquire(("page", page_id), ("config", "config")):
        try:
            before = read_json(path)
        except FileNotFoundError:
            raise ConfigNotFoundError(f"Page '{page_id}' not found") from None
        path.unlink(missing_ok=True)
        invalidate_runtime_pages_config_cache()
        config = _read_config_index()
        pages_index = config.get("pages")
        if isinstance(pages_index, list) and remove_page(pages_index, page_id):
            _write_config_index(config)
        response = applied_response(f"Deleted page '{page_id}'", before, None)
    await emit_change(
        artifact_type="page",
        artifact_ids=[page_id],
        summary=response["summary"],
        diff=response["diff"]
    )
    if idempotency_key:
        idempotency.put(label, idempotency_key, response)
    return response


@register_tool()
async def pages_set_metadata(
    page_id: str,
    patch: dict[str, Any],
    idempotency_key: str | None = None,
) -> dict[str, Any]:
    """Apply a JSON Merge Patch (RFC 7396) to the page's metadata fields."""
    label = get_agent_label()
    if idempotency_key:
        cached = idempotency.get(label, idempotency_key)
        if cached is not None:
            return cached
    if not is_valid_page_id(page_id):
        raise ConfigValidationError("Invalid page_id")
    if not isinstance(patch, dict):
        raise ConfigValidationError("patch must be an object")
    disallowed = set(patch.keys()) - _PAGE_METADATA_FIELDS
    if disallowed:
        raise ConfigValidationError(
            f"pages_set_metadata patch may only contain {sorted(_PAGE_METADATA_FIELDS)}; "
            f"got {sorted(disallowed)}"
        )
    async with locks.acquire(("page", page_id)):
        before = _read_page(page_id)
        after = copy.deepcopy(before)
        merge_patch(after, patch)
        warnings = _validate_page_or_raise(after)
        _write_page(page_id, after)
        response = applied_response(
            f"Updated metadata on '{page_id}'", before, after, warnings=warnings
        )
    await emit_change(
        artifact_type="page",
        artifact_ids=[page_id],
        summary=response["summary"],
        diff=response["diff"]
    )
    if idempotency_key:
        idempotency.put(label, idempotency_key, response)
    return response


@register_tool()
async def pages_add_widget(
    page_id: str,
    widget: dict[str, Any],
    parent_id: str | None = None,
    index: int | None = None,
    before_id: str | None = None,
    after_id: str | None = None,
    idempotency_key: str | None = None,
) -> dict[str, Any]:
    """Add a widget under ``parent_id`` (or root if ``parent_id`` omitted).

    ``widget`` is the widget JSON minus ``id`` — the server assigns one.
    Exactly one of ``index`` / ``before_id`` / ``after_id`` must be supplied.
    """
    label = get_agent_label()
    if idempotency_key:
        cached = idempotency.get(label, idempotency_key)
        if cached is not None:
            return cached
    if not is_valid_page_id(page_id):
        raise ConfigValidationError("Invalid page_id")
    if not isinstance(widget, dict) or not widget.get("type"):
        raise ConfigValidationError("widget.type is required")
    async with locks.acquire(("page", page_id)):
        before = _read_page(page_id)
        after = copy.deepcopy(before)
        widget_type = widget["type"]
        new_widget: dict[str, Any] = copy.deepcopy(widget)
        # Rewrite IDs across the whole subtree — caller-supplied IDs (from
        # copy-pasted JSON or a prior tool result) would otherwise collide
        # with widgets already on the page.
        page_ids: set[str] = set()
        _collect_widget_ids(after, page_ids)
        _assign_fresh_widget_ids(new_widget, page_ids)
        widget_id = new_widget["id"]
        if "name" not in new_widget:
            new_widget["name"] = _widget_name_for(widget_type)
        if _hosts_children(widget_type) and "children" not in new_widget:
            new_widget["children"] = []
        children = parent_children_list(after, parent_id)
        # Replace in place since parent_children_list returned a reference.
        children[:] = insert_at_position(
            children, new_widget, index=index, before_id=before_id, after_id=after_id
        )
        warnings = _validate_page_or_raise(after)
        _write_page(page_id, after)
        response = applied_response(
            f"Added {widget.get('type')} widget '{widget_id}' to '{page_id}'",
            before,
            after,
            warnings=warnings,
        )
        response["widget_id"] = widget_id
    await emit_change(
        artifact_type="page",
        artifact_ids=[page_id],
        summary=response["summary"],
        diff=response["diff"]
    )
    if idempotency_key:
        idempotency.put(label, idempotency_key, response)
    return response


@register_tool()
async def pages_delete_widget(
    page_id: str,
    widget_id: str,
    confirm: bool = False,
    idempotency_key: str | None = None,
) -> dict[str, Any]:
    """Delete a widget by ID. Two-step: dry-run unless ``confirm=true``."""
    label = get_agent_label()
    if idempotency_key:
        cached = idempotency.get(label, idempotency_key)
        if cached is not None:
            return cached
    if not is_valid_page_id(page_id):
        raise ConfigValidationError("Invalid page_id")
    async with locks.acquire(("page", page_id)):
        before = _read_page(page_id)
        after = copy.deepcopy(before)
        found = find_widget(after, widget_id)
        if found is None:
            raise ConfigValidationError(f"Widget '{widget_id}' not found in page '{page_id}'")
        widget, parent_list = found
        if not confirm:
            preview = copy.deepcopy(before)
            preview_found = find_widget(preview, widget_id)
            if preview_found is not None:
                preview_widget, preview_parent = preview_found
                preview_parent.remove(preview_widget)
            return dry_run_response(
                f"Would delete widget '{widget_id}' from '{page_id}'",
                before,
                preview,
            )
        parent_list.remove(widget)
        warnings = _validate_page_or_raise(after)
        _write_page(page_id, after)
        response = applied_response(
            f"Deleted widget '{widget_id}' from '{page_id}'", before, after, warnings=warnings
        )
    await emit_change(
        artifact_type="page",
        artifact_ids=[page_id],
        summary=response["summary"],
        diff=response["diff"]
    )
    if idempotency_key:
        idempotency.put(label, idempotency_key, response)
    return response


@register_tool()
async def pages_set_widget_property(
    page_id: str,
    widget_id: str,
    property: str,
    value: Any,
    idempotency_key: str | None = None,
) -> dict[str, Any]:
    """Set a single widget property by JSON Pointer (RFC 6901).

    Examples: ``/label`` sets ``properties.label``; ``/style/backgroundColor``
    sets ``properties.style.backgroundColor``; ``/actions/0/target`` sets the
    first action's target. ``value`` may be any property source
    (``$static``, ``$var``, ``$if``, …) — variable binding is just
    ``{"$var": {"path": "datasource:location"}}``.
    """
    label = get_agent_label()
    if idempotency_key:
        cached = idempotency.get(label, idempotency_key)
        if cached is not None:
            return cached
    if not is_valid_page_id(page_id):
        raise ConfigValidationError("Invalid page_id")
    async with locks.acquire(("page", page_id)):
        before = _read_page(page_id)
        after = copy.deepcopy(before)
        found = find_widget(after, widget_id)
        if found is None:
            raise ConfigValidationError(f"Widget '{widget_id}' not found in page '{page_id}'")
        widget, _parent = found
        apply_json_pointer(widget, property, value)
        warnings = _validate_page_or_raise(after)
        _write_page(page_id, after)
        response = applied_response(
            f"Set {property} on widget '{widget_id}' in '{page_id}'", before, after, warnings=warnings
        )
    await emit_change(
        artifact_type="page",
        artifact_ids=[page_id],
        summary=response["summary"],
        diff=response["diff"]
    )
    if idempotency_key:
        idempotency.put(label, idempotency_key, response)
    return response
