import type { Icon } from '@phosphor-icons/react';
import {
  ActivityIcon,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowsClockwise,
  ArrowsInLineHorizontal,
  ArrowsLeftRight,
  ArrowsOutLineHorizontal,
  ArrowUp,
  Barcode,
  BatteryFull,
  Bell,
  Broadcast,
  Browsers,
  Bug,
  Calendar,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  ChartBar,
  ChartDonut,
  ChartLine,
  ChartPie,
  ChartScatter,
  Check,
  CheckCircle,
  Circuitry,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Cloud,
  Columns,
  Copy,
  Cpu,
  Crosshair,
  Cube,
  CursorClick,
  Database,
  DotsThree,
  DownloadSimple,
  Drop,
  Engine,
  Envelope,
  Export,
  Eye,
  EyeSlash,
  Factory,
  Fan,
  FileText,
  Fire,
  Flask,
  FloppyDisk,
  FlowArrow,
  Folder,
  FrameCorners,
  Funnel,
  Gauge,
  GearSix,
  Graph,
  HandPalm,
  HardDrives,
  Hourglass,
  House,
  ImageSquare,
  Info,
  Lightbulb,
  Lightning,
  List,
  Lock,
  MagnifyingGlass,
  MapPin,
  Minus,
  Note,
  Package,
  Path,
  Pause,
  PencilSimple,
  Pipe,
  Play,
  Plug,
  Plus,
  Power,
  Printer,
  Prohibit,
  PuzzlePiece,
  QrCode,
  Question,
  Rows,
  Ruler,
  Scales,
  SealCheck,
  ShieldCheck,
  SidebarSimple,
  SignOut,
  Siren,
  SlidersHorizontal,
  Snowflake,
  Speedometer,
  SquaresFour,
  Stack,
  Star,
  Stop,
  Table,
  Tag,
  Target,
  Terminal,
  TextT,
  Thermometer,
  Timer,
  Toolbox,
  Translate,
  Trash,
  TreeStructure,
  TrendDown,
  TrendUp,
  UploadSimple,
  User,
  Users,
  Warning,
  WarningCircle,
  WaveSine,
  WifiHigh,
  WifiSlash,
  Wind,
  Wrench,
  X,
  XCircle,
} from '@phosphor-icons/react';

type IconComponent = Icon;

// Static id → component map. Explicit named imports (rather than a
// `import * as` namespace with dynamic lookup) let the bundler tree-shake the
// Phosphor library down to just the icons the app actually uses — the whole
// set is ~5 MB, this allowlisted subset is ~94 kB gzip.
//
// This module is its own chunk (backlog item 22). `phosphorIcons.tsx`'s HMI
// runtime accessor (`getBuiltinIconComponent`) reaches it via a per-icon
// dynamic `import()`, so a route only pulls the vendor-icons chunk once a
// widget actually renders a builtin icon. Editor authoring surfaces
// (WidgetIcon, IconSourcePicker) need the full set rendered synchronously and
// import this map directly instead — see those files for why.
export const BUILTIN_ICON_COMPONENTS: Record<string, IconComponent> = {
  activity: ActivityIcon,
  'arrow-clockwise': ArrowClockwise,
  'arrow-counter-clockwise': ArrowCounterClockwise,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrows-clockwise': ArrowsClockwise,
  'arrows-in-line-horizontal': ArrowsInLineHorizontal,
  'arrows-left-right': ArrowsLeftRight,
  'arrows-out-line-horizontal': ArrowsOutLineHorizontal,
  barcode: Barcode,
  'battery-full': BatteryFull,
  bell: Bell,
  broadcast: Broadcast,
  browsers: Browsers,
  bug: Bug,
  calendar: Calendar,
  'caret-down': CaretDown,
  'caret-left': CaretLeft,
  'caret-right': CaretRight,
  'caret-up': CaretUp,
  'chart-bar': ChartBar,
  'chart-donut': ChartDonut,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'chart-scatter': ChartScatter,
  check: Check,
  'check-circle': CheckCircle,
  circuitry: Circuitry,
  'clipboard-text': ClipboardText,
  clock: Clock,
  'clock-counter-clockwise': ClockCounterClockwise,
  cloud: Cloud,
  columns: Columns,
  copy: Copy,
  cpu: Cpu,
  crosshair: Crosshair,
  cube: Cube,
  'cursor-click': CursorClick,
  database: Database,
  'dots-three': DotsThree,
  'download-simple': DownloadSimple,
  drop: Drop,
  engine: Engine,
  envelope: Envelope,
  export: Export,
  eye: Eye,
  'eye-slash': EyeSlash,
  factory: Factory,
  fan: Fan,
  'file-text': FileText,
  fire: Fire,
  flask: Flask,
  'floppy-disk': FloppyDisk,
  'flow-arrow': FlowArrow,
  folder: Folder,
  'frame-corners': FrameCorners,
  funnel: Funnel,
  gauge: Gauge,
  'gear-six': GearSix,
  graph: Graph,
  'hand-palm': HandPalm,
  'hard-drives': HardDrives,
  hourglass: Hourglass,
  house: House,
  'image-square': ImageSquare,
  info: Info,
  lightbulb: Lightbulb,
  lightning: Lightning,
  list: List,
  lock: Lock,
  'magnifying-glass': MagnifyingGlass,
  'map-pin': MapPin,
  minus: Minus,
  note: Note,
  package: Package,
  path: Path,
  pause: Pause,
  'pencil-simple': PencilSimple,
  pipe: Pipe,
  play: Play,
  plug: Plug,
  plus: Plus,
  power: Power,
  printer: Printer,
  prohibit: Prohibit,
  'puzzle-piece': PuzzlePiece,
  'qr-code': QrCode,
  question: Question,
  rows: Rows,
  ruler: Ruler,
  scales: Scales,
  'seal-check': SealCheck,
  'shield-check': ShieldCheck,
  'sidebar-simple': SidebarSimple,
  'sign-out': SignOut,
  siren: Siren,
  'sliders-horizontal': SlidersHorizontal,
  snowflake: Snowflake,
  speedometer: Speedometer,
  'squares-four': SquaresFour,
  stack: Stack,
  star: Star,
  stop: Stop,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  'text-t': TextT,
  thermometer: Thermometer,
  timer: Timer,
  toolbox: Toolbox,
  translate: Translate,
  trash: Trash,
  'tree-structure': TreeStructure,
  'trend-down': TrendDown,
  'trend-up': TrendUp,
  'upload-simple': UploadSimple,
  user: User,
  users: Users,
  warning: Warning,
  'warning-circle': WarningCircle,
  'wave-sine': WaveSine,
  'wifi-high': WifiHigh,
  'wifi-slash': WifiSlash,
  wind: Wind,
  wrench: Wrench,
  x: X,
  'x-circle': XCircle,
};
