interface BuiltinIconOption {
  id: string;
  label: string;
}

// Curated built-in icons exposed in Config picker and HMI runtime.
export const BUILTIN_ICON_ALLOWLIST: BuiltinIconOption[] = [
  { id: 'house', label: 'House' },
  { id: 'gauge', label: 'Gauge' },
  { id: 'cpu', label: 'CPU' },
  { id: 'thermometer', label: 'Thermometer' },
  { id: 'drop', label: 'Drop' },
  { id: 'wave-sine', label: 'Wave' },
  { id: 'lightning', label: 'Lightning' },
  { id: 'warning', label: 'Warning' },
  { id: 'warning-circle', label: 'Warning Circle' },
  { id: 'x-circle', label: 'Error Circle' },
  { id: 'check-circle', label: 'Check Circle' },
  { id: 'info', label: 'Info' },
  { id: 'play', label: 'Play' },
  { id: 'pause', label: 'Pause' },
  { id: 'stop', label: 'Stop' },
  { id: 'cursor-click', label: 'Cursor Click' },
  { id: 'arrow-clockwise', label: 'Refresh' },
  { id: 'arrows-clockwise', label: 'Sync' },
  { id: 'arrows-left-right', label: 'Left / Right' },
  { id: 'arrows-in-line-horizontal', label: 'Horizontal Contract' },
  { id: 'arrows-out-line-horizontal', label: 'Horizontal Expand' },
  { id: 'sliders-horizontal', label: 'Sliders' },
  { id: 'gear-six', label: 'Settings' },
  { id: 'wrench', label: 'Wrench' },
  { id: 'toolbox', label: 'Toolbox' },
  { id: 'database', label: 'Database' },
  { id: 'plug', label: 'Plug' },
  { id: 'broadcast', label: 'Broadcast' },
  { id: 'chart-line', label: 'Chart Line' },
  { id: 'chart-bar', label: 'Chart Bar' },
  { id: 'trend-up', label: 'Trend Up' },
  { id: 'trend-down', label: 'Trend Down' },
  { id: 'activity', label: 'Activity' },
  { id: 'clock', label: 'Clock' },
  { id: 'clock-counter-clockwise', label: 'History' },
  { id: 'calendar', label: 'Calendar' },
  { id: 'user', label: 'User' },
  { id: 'users', label: 'Users' },
  { id: 'eye', label: 'Eye' },
  { id: 'eye-slash', label: 'Eye Slash' },
  { id: 'lock', label: 'Lock' },
  { id: 'shield-check', label: 'Shield Check' },
  { id: 'bell', label: 'Bell' },
  { id: 'list', label: 'List' },
  { id: 'squares-four', label: 'Grid' },
  { id: 'stack', label: 'Stack' },
  { id: 'browsers', label: 'Tabs' },
  { id: 'sidebar-simple', label: 'Sidebar' },
  { id: 'frame-corners', label: 'Frame' },
  { id: 'path', label: 'Path' },
  { id: 'text-t', label: 'Text' },
  { id: 'translate', label: 'Translate' },
  { id: 'puzzle-piece', label: 'Puzzle Piece' },
  { id: 'star', label: 'Star' },
  { id: 'file-text', label: 'File Text' },
  { id: 'folder', label: 'Folder' },
  { id: 'image-square', label: 'Image' },
  { id: 'columns', label: 'Columns' },
  { id: 'cube', label: 'Cube' },
  // Process and equipment
  { id: 'fan', label: 'Fan' },
  { id: 'engine', label: 'Engine' },
  { id: 'pipe', label: 'Pipe' },
  { id: 'flask', label: 'Flask' },
  { id: 'funnel', label: 'Filter' },
  { id: 'factory', label: 'Factory' },
  { id: 'package', label: 'Package' },
  { id: 'barcode', label: 'Barcode' },
  { id: 'qr-code', label: 'QR Code' },
  { id: 'scales', label: 'Scales' },
  { id: 'ruler', label: 'Ruler' },
  { id: 'wind', label: 'Wind' },
  { id: 'snowflake', label: 'Snowflake' },
  { id: 'fire', label: 'Fire' },
  { id: 'siren', label: 'Siren' },
  { id: 'lightbulb', label: 'Lightbulb' },
  { id: 'circuitry', label: 'Circuitry' },
  { id: 'timer', label: 'Timer' },
  { id: 'hourglass', label: 'Hourglass' },
  { id: 'speedometer', label: 'Speedometer' },
  // Editing and actions
  { id: 'plus', label: 'Plus' },
  { id: 'minus', label: 'Minus' },
  { id: 'check', label: 'Check' },
  { id: 'x', label: 'Close' },
  { id: 'pencil-simple', label: 'Pencil' },
  { id: 'trash', label: 'Trash' },
  { id: 'floppy-disk', label: 'Save' },
  { id: 'download-simple', label: 'Download' },
  { id: 'upload-simple', label: 'Upload' },
  { id: 'export', label: 'Export' },
  { id: 'copy', label: 'Copy' },
  { id: 'magnifying-glass', label: 'Search' },
  { id: 'printer', label: 'Printer' },
  { id: 'arrow-counter-clockwise', label: 'Undo' },
  // Navigation and arrows
  { id: 'caret-up', label: 'Caret Up' },
  { id: 'caret-down', label: 'Caret Down' },
  { id: 'caret-left', label: 'Caret Left' },
  { id: 'caret-right', label: 'Caret Right' },
  { id: 'arrow-up', label: 'Arrow Up' },
  { id: 'arrow-down', label: 'Arrow Down' },
  { id: 'arrow-left', label: 'Arrow Left' },
  { id: 'arrow-right', label: 'Arrow Right' },
  { id: 'dots-three', label: 'More' },
  { id: 'sign-out', label: 'Sign Out' },
  { id: 'power', label: 'Power' },
  { id: 'question', label: 'Question' },
  { id: 'prohibit', label: 'Prohibit' },
  { id: 'hand-palm', label: 'Hand' },
  { id: 'target', label: 'Target' },
  { id: 'crosshair', label: 'Crosshair' },
  { id: 'map-pin', label: 'Map Pin' },
  // Status, data and connectivity
  { id: 'wifi-high', label: 'Wi-Fi' },
  { id: 'wifi-slash', label: 'Wi-Fi Off' },
  { id: 'cloud', label: 'Cloud' },
  { id: 'hard-drives', label: 'Hard Drives' },
  { id: 'terminal', label: 'Terminal' },
  { id: 'bug', label: 'Bug' },
  { id: 'battery-full', label: 'Battery' },
  { id: 'table', label: 'Table' },
  { id: 'rows', label: 'Rows' },
  { id: 'tree-structure', label: 'Tree Structure' },
  { id: 'flow-arrow', label: 'Flow Arrow' },
  { id: 'graph', label: 'Graph' },
  { id: 'chart-pie', label: 'Chart Pie' },
  { id: 'chart-donut', label: 'Chart Donut' },
  { id: 'chart-scatter', label: 'Chart Scatter' },
  { id: 'clipboard-text', label: 'Clipboard' },
  { id: 'note', label: 'Note' },
  { id: 'tag', label: 'Tag' },
  { id: 'envelope', label: 'Envelope' },
  { id: 'seal-check', label: 'Verified' },
] as const;

export const BUILTIN_ICON_IDS = new Set(BUILTIN_ICON_ALLOWLIST.map((icon) => icon.id));
