/**
 * The user guide's widget catalog and property-source table are generated from
 * this registry, not hand-written. Before that, the published catalog was 17
 * hand-copied cards against 18 registered widgets and had already lost
 * StatusPill.
 *
 * Normal runs assert the committed output still matches the registry — that is
 * the drift guard. `npm run docs:widgets` sets UPDATE_DOCS=1 and rewrites it.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildCatalog } from '@config/components/ui/WidgetSelector/catalog';
import { widgetRegistry } from './widgetRegistry';
import { PROPERTY_SOURCES } from '@hmi/utils/propertySourceRegistry';
import { VALUE_TYPES } from '@shared/utils/valueTypes';

const GUIDE_DIR = resolve(__dirname, '../../../../docs/user');
const GENERATED_DIR = resolve(GUIDE_DIR, 'generated');

interface GeneratedProp {
  key: string;
  label: string;
  type: string;
  /** Section the editor files the property under; absent means the default
   *  "Properties" list. */
  group?: string;
  /** The value in effect when the property is unset. Published because it is
   *  otherwise invisible outside the editor. */
  defaultValue?: unknown;
}

interface GeneratedWidget {
  type: string;
  name: string;
  description: string;
  props: GeneratedProp[];
}

// Simple types are matched case-insensitively at runtime (valueTypes.ts's
// CANONICAL_BY_LOWER), so a stdlib widget's `'string'` and a registry entry's
// `'String'` mean the same thing. The published catalog should not expose that
// authoring difference as two spellings of one type.
const CANONICAL_TYPE = new Map(VALUE_TYPES.map((t) => [t.toLowerCase(), t as string]));

function displayType(type: string | string[]): string {
  const one = (t: string) => {
    const array = t.endsWith('[]');
    const base = array ? t.slice(0, -2) : t;
    const canonical = CANONICAL_TYPE.get(base.toLowerCase()) ?? base;
    return array ? `${canonical}[]` : canonical;
  };
  return Array.isArray(type) ? type.map(one).join(' | ') : one(type);
}

function buildWidgets(): { category: string; widgets: GeneratedWidget[] }[] {
  return buildCatalog().map(({ category, items }) => ({
    category,
    widgets: items.map((item) => {
      const schema = widgetRegistry[item.type]?.schema ?? {};
      return {
        type: item.type,
        name: item.name,
        description: item.description ?? '',
        props: Object.entries(schema).map(([key, field]) => ({
          key,
          label: field.label,
          type: displayType(field.type),
          ...(field.group === undefined ? {} : { group: field.group }),
          ...(field.defaultValue === undefined ? {} : { defaultValue: field.defaultValue }),
        })),
      };
    }),
  }));
}

function buildPropertySources() {
  // PROPERTY_SOURCES is keyed by `source`, not by the persisted `$`-key.
  return Object.values(PROPERTY_SOURCES).map((descriptor) => ({
    key: descriptor.key,
    label: descriptor.label,
    description: descriptor.description,
    produces: descriptor.produces,
  }));
}

/** The catalog page itself — generated so GitHub and the rendered site agree. */
function buildCatalogPage(): string {
  const lines: string[] = [
    '<!-- Generated by `npm run docs:widgets` from widgetRegistry.tsx. Do not edit. -->',
    '',
    '# Built-in widget catalog',
    '',
    'The widgets that ship in the box, grouped by job, each with the properties you',
    'can set. Bind any of them to live data like any other field.',
    '',
  ];
  for (const { category, widgets } of buildWidgets()) {
    lines.push(`## ${category}`, '');
    for (const widget of widgets) {
      lines.push(`### ${widget.name}`, '', widget.description, '');
      if (widget.props.length > 0) {
        lines.push('| Property | Label | Type |', '|---|---|---|');
        for (const prop of widget.props) {
          lines.push(`| \`${prop.key}\` | ${prop.label} | \`${prop.type}\` |`);
        }
        lines.push('');
      }
    }
  }
  lines.push(
    'Beyond these you have **Components** (reusable page fragments with input',
    'properties) and every **custom widget** in the active project. They all live in',
    'the same Add-widget menu — see [Building your own widgets](custom-widgets.md).',
    '',
  );
  return lines.join('\n');
}

function checkText(path: string, serialized: string, name: string): void {
  if (process.env.UPDATE_DOCS === '1') {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, serialized, 'utf-8');
    return;
  }
  expect(existsSync(path), `${name} is missing — run \`npm run docs:widgets\``).toBe(true);
  expect(readFileSync(path, 'utf-8'), `${name} is stale — run \`npm run docs:widgets\``).toBe(
    serialized,
  );
}

function checkJson(name: string, value: unknown): void {
  checkText(resolve(GENERATED_DIR, name), `${JSON.stringify(value, null, 2)}\n`, name);
}

describe('generated documentation metadata', () => {
  it('widgets.json matches the registry', () => {
    checkJson('widgets.json', buildWidgets());
  });

  it('property-sources.json matches the source registry', () => {
    checkJson('property-sources.json', buildPropertySources());
  });

  it('catalog.md matches the registry', () => {
    checkText(resolve(GUIDE_DIR, 'catalog.md'), buildCatalogPage(), 'catalog.md');
  });
});
